language: node_js
node_js: 14
dist: trusty
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: public
    target_branch: gh-pages
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master